"""empty message

Revision ID: e9dd120d2954
Revises: 04000f03332b
Create Date: 2021-02-13 17:12:27.768364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dd120d2954'
down_revision = '04000f03332b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoapp', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todoapp SET completed = False WHERE completed IS NULL;')
    op.alter_column('todoapp', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoapp', 'completed')
    # ### end Alembic commands ###
